name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/image-15.png
    - assets/page-1/images/qr-code.png
    - assets/page-1/images/qr-code-bfA.png
    - assets/page-1/images/receipt.png
    - assets/page-1/images/form.png
    - assets/page-1/images/estimates.png
    - assets/page-1/images/image-20.png
    - assets/page-1/images/home-page.png
    - assets/page-1/images/parcking-ticket-Z3a.png
    - assets/page-1/images/add-user-male.png
    - assets/page-1/images/parcking-ticket.png
    - assets/page-1/images/parcking-ticket-Qdz.png
    - assets/page-1/images/image-16.png
    - assets/page-1/images/form-Egk.png
    - assets/page-1/images/home-page-aAp.png
    - assets/page-1/images/home-page-f48.png
    - assets/page-1/images/info.png
    - assets/page-1/images/receipt-Xkg.png
    - assets/page-1/images/home-page-SzY.png
    - assets/page-1/images/form-mhN.png
    - assets/page-1/images/receipt-kh2.png
    - assets/page-1/images/add-user-male-pqA.png
    - assets/page-1/images/hourglass-6mi.png
    - assets/page-1/images/parcking-ticket-Npc.png
    - assets/page-1/images/home-page-j9N.png
    - assets/page-1/images/arrow-1.png
    - assets/page-1/images/ellipse-7.png
    - assets/page-1/images/image-22.png
    - assets/page-1/images/receipt-EMa.png
    - assets/page-1/images/parcking-ticket-EXv.png
    - assets/page-1/images/image-22-VeC.png
    - assets/page-1/images/hourglass.png
    - assets/page-1/images/home-page-MHe.png
    - assets/page-1/images/add-user-male-5AL.png
    - assets/page-1/images/hourglass-Moz.png
    - assets/page-1/images/about-us-bg.png
    - assets/page-1/images/qr-bg.png
    - assets/page-1/images/ellipse-3.png
    - assets/page-1/images/home-page-yzk.png
    - assets/page-1/images/ellipse-5.png
    - assets/page-1/images/image-19.png
    - assets/page-1/images/form-UNx.png
    - assets/page-1/images/receipt-2fN.png
    - assets/page-1/images/ellipse-4.png
    - assets/page-1/images/ellipse-7-NUt.png
    - assets/page-1/images/letter.png
    - assets/page-1/images/ellipse-9.png
    - assets/page-1/images/parking-bg.png
    - assets/page-1/images/registrar-bg.png
    - assets/page-1/images/rectangle-2.png
    - assets/page-1/images/estimates-u1n.png
    - assets/page-1/images/estimates-wUG.png
    - assets/page-1/images/parcking-ticket-Vkg.png
    - assets/page-1/images/receipt-s6C.png
    - assets/page-1/images/ellipse-5-zAp.png
    - assets/page-1/images/parcking-ticket-wbr.png
    - assets/page-1/images/estimates-kZJ.png
    - assets/page-1/images/receipt-7Pr.png
    - assets/page-1/images/ellipse-3-n9i.png
    - assets/page-1/images/phone.png
    - assets/page-1/images/ellipse-7-uVE.png
    - assets/page-1/images/phone-58p.png
    - assets/page-1/images/info-iSg.png
    - assets/page-1/images/info-Br4.png
    - assets/page-1/images/ellipse-3-ami.png
    - assets/page-1/images/estimates-9K2.png
    - assets/page-1/images/tellering-bg.png
    - assets/page-1/images/form-h5e.png
    - assets/page-1/images/phone-fHN.png
    - assets/page-1/images/rectangle-2-2Np.png
    - assets/page-1/images/group-7.png
    - assets/page-1/images/accounting-bg.png
    - assets/page-1/images/parcking-ticket-9iL.png
    - assets/page-1/images/ellipse-8.png
    - assets/page-1/images/form-fKJ.png
    - assets/page-1/images/arrow-1-bcG.png
    - assets/page-1/images/home.png
    - assets/page-1/images/ellipse-3-j2C.png
    - assets/page-1/images/ellipse-3-HJc.png
    - assets/page-1/images/auto-group-czf5.png
    - assets/page-1/images/letter-VvU.png
    - assets/page-1/images/ellipse-4-Ca8.png
    - assets/page-1/images/ellipse-3-ah2.png
    - assets/page-1/images/ellipse-3-j48.png
    - assets/page-1/images/estimates-MPS.png
    - assets/page-1/images/rectangle-2-i4t.png
    - assets/page-1/images/receipt-v36.png
    - assets/page-1/images/image-21.png
    - assets/page-1/images/home-page-dCQ.png
    - assets/page-1/images/home-page-adS.png
    - assets/page-1/images/ellipse-7-k28.png
    - assets/page-1/images/ellipse-3-uue.png
    - assets/page-1/images/qccccc-removebg-preview-1.png
    - assets/page-1/images/ellipse-8-hJ4.png
    - assets/page-1/images/estimates-Eon.png
    - assets/page-1/images/form-Ckc.png
    - assets/page-1/images/receipt-YJg.png
    - assets/page-1/images/ellipse-9-S2g.png
    - assets/page-1/images/estimates-CpC.png
    - assets/page-1/images/image-4.png
    - assets/page-1/images/parcking-ticket-8Sx.png
    - assets/page-1/images/estimates-6eg.png
    - assets/page-1/images/letter-PYQ.png
    - assets/page-1/images/receipt-91n.png
    - assets/page-1/images/letter-hJC.png
    - assets/page-1/images/image-23.png
    - assets/page-1/images/ellipse-5-2zg.png
    - assets/page-1/images/home-page-B6t.png
    - assets/page-1/images/ellipse-5-icc.png
    - assets/page-1/images/form-pfe.png
    - assets/page-1/images/home-page-yYY.png
    - assets/page-1/images/ellipse-7-jGp.png
    - assets/page-1/images/image-14.png
    - assets/page-1/images/form-sdW.png
    - assets/page-1/images/image-12.png
    - assets/page-1/images/image-17.png
    - assets/page-1/images/phone-4JQ.png
    - assets/page-1/images/form-jKJ.png
    - assets/page-1/images/image-12-UGt.png
    - assets/page-1/images/ellipse-3-xCc.png
    - assets/page-1/images/auto-group-tvzj.png
    - assets/page-1/images/image-18.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
